language: node_js
node_js:
- '5'
branches:
  only:
  - develop
  - master
sudo: required
services:
- docker
env:
  matrix:
  - global:
    - DOCKER_COMPOSE_VERSION: 2
    - REPO=mejelly/jello-$TRAVIS_BRANCH
    - COMMIT=${TRAVIS_COMMIT::8}
before_install:
  - openssl aes-256-cbc -K $encrypted_9f5b86caa04f_key -iv $encrypted_9f5b86caa04f_iv -in .travis/deploy_rsa.enc -out .travis/deploy_key -d
before_script:
  - docker build -t $REPO:$COMMIT -f compose/passenger/Dockerfile .
  - docker-compose -f docker-compose.yml up -d
script:
  - sleep 5
  - docker-compose -f docker-compose.yml run web rails cucumber
  - docker-compose -f docker-compose.yml run web rails assets:precompile
after_script:
  - docker-compose down
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push $REPO
