version: '2'
services:
  db:
    image: postgres
  web:
    image: "${REPO}:${COMMIT}"
    build:
      context: .
      dockerfile: compose/passenger/Dockerfile
    entrypoint: /entrypoint.sh
    command: /start-dev.sh
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - KNAPSACK_PRO_TEST_SUITE_TOKEN_MINITEST=$KNAPSACK_PRO_TEST_SUITE_TOKEN_MINITEST
      - CI=$CI
      - TRAVIS=$TRAVIS
      - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
      - AUTH0_CLIENT_ID=AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
      - AUTH0_DOMAIN=$AUTH0_DOMAIN
      - AUTH0_CALLBACK_URL=$AUTH0_CALLBACK_URL
