version: '2'
services:
  db:
    image: postgres
  web:
    image: "${REPO}:${COMMIT}"
    build:
      context: .
      dockerfile: mejelly/compose/passenger/Dockerfile
    entrypoint: /entrypoint.sh
    command: /start-dev.sh
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      - KNAPSACK_PRO_TEST_SUITE_TOKEN_MINITEST=$KNAPSACK_PRO_TEST_SUITE_TOKEN_MINITEST
      - CI=$CI
      - TRAVIS=$TRAVIS
      - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
