version: '2'
services:
  db:
    image: postgres
    volumes:
      - /private/var/lib/docker/mejelly-data:/var/lib/postgresql/data
  web:
    image: {}
    build:
      context: .
      dockerfile: compose/passenger/Dockerfile
    entrypoint: /entrypoint.sh
    command: /sbin/my_init
    depends_on:
      - db
    ports:
      - "0.0.0.0:3001:443"
    dns:
      - 8.8.8.8
    environment:
      - KNAPSACK_PRO_TEST_SUITE_TOKEN_MINITEST=$KNAPSACK_PRO_TEST_SUITE_TOKEN_MINITEST
      - CI=$CI
      - TRAVIS=$TRAVIS
      - COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN
      - AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET=$AUTH0_CLIENT_SECRET
      - AUTH0_DOMAIN=$AUTH0_DOMAIN
      - AUTH0_CALLBACK_URL=$AUTH0_CALLBACK_URL
      - AUTH0_REDIRECT_URL=$AUTH0_REDIRECT_URL
      - GITHUB_USERNAME=$GITHUB_USERNAME
      - GITHUB_PASSWORD=$GITHUB_PASSWORD
      - MEJELLY_SECRET_KEY_BASE=$MEJELLY_SECRET_KEY_BASE
